# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run for rajini
        run: echo superstar*!
        
        # Runs a single command using the runners shell
      - name: Installing SAST tool bandit
        run: pip install bandit
        
        # Runs a single command using the runners shell
      - name: Running bandit and json outout
        continue-on-error: true
        run: bandit -r ./ -f json -o djangovuln_results.json
        
        
        # Runs a single command using the runners shell
      - name: test job
        run: echo 'true' 
        
      - uses: actions/upload-artifact@v3
        with:
         name: django-output
         path: djangovuln_results.json
         
         # Runs a single command using the runners shell
      - name: Installing Trufflehog for secret scan
        run:  pip install trufflehog3
        
        # Runs a single command using the runners shell
      - name: Running Trufflehog for secret scan
        run:  trufflehog3 -R
         
       
    
        
   

      
